package com.model;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class TGoods implements java.io.Serializable {
	private Integer goodsId;
	private String paijia;
	private String goodsName;
	private String goodsMiaoshu;
	private String fujian;
	private Integer goodsDijia;
	private Integer goodsCatelogId;
	private Integer goodsUserId;
	private String goodsShijian;
	private String goodsDel;
	private String erweima;
	
	public String getPaijia() {
		return paijia;
	}

	public void setPaijia(String paijia) {
		this.paijia = paijia;
	}

	// Constructors

	public String getErweima() {
		return erweima;
	}

	public void setErweima(String erweima) {
		this.erweima = erweima;
	}

	/** default constructor */
	public TGoods() {
	}

	/** full constructor */
	public TGoods(String goodsName, String goodsMiaoshu, Integer goodsDijia,
			Integer goodsCatelogId, Integer goodsUserId, String goodsDel) {
		this.goodsName = goodsName;
		this.goodsMiaoshu = goodsMiaoshu;
		this.goodsDijia = goodsDijia;
		this.goodsCatelogId = goodsCatelogId;
		this.goodsUserId = goodsUserId;
		this.goodsDel = goodsDel;
	}

	public TGoods(Integer goodsId, String paijia, String goodsName,
			String goodsMiaoshu, String fujian, Integer goodsDijia,
			Integer goodsCatelogId, Integer goodsUserId, String goodsShijian,
			String goodsDel, String erweima) {
		super();
		this.goodsId = goodsId;
		this.paijia = paijia;
		this.goodsName = goodsName;
		this.goodsMiaoshu = goodsMiaoshu;
		this.fujian = fujian;
		this.goodsDijia = goodsDijia;
		this.goodsCatelogId = goodsCatelogId;
		this.goodsUserId = goodsUserId;
		this.goodsShijian = goodsShijian;
		this.goodsDel = goodsDel;
		this.erweima = erweima;
	}

	public Integer getGoodsId() {
		return this.goodsId;
	}

	public String getGoodsShijian() {
		return goodsShijian;
	}

	public void setGoodsShijian(String goodsShijian) {
		this.goodsShijian = goodsShijian;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getGoodsMiaoshu() {
		return this.goodsMiaoshu;
	}

	public void setGoodsMiaoshu(String goodsMiaoshu) {
		this.goodsMiaoshu = goodsMiaoshu;
	}

	public Integer getGoodsDijia() {
		return this.goodsDijia;
	}

	public void setGoodsDijia(Integer goodsDijia) {
		this.goodsDijia = goodsDijia;
	}

	public Integer getGoodsCatelogId() {
		return this.goodsCatelogId;
	}

	public void setGoodsCatelogId(Integer goodsCatelogId) {
		this.goodsCatelogId = goodsCatelogId;
	}

	public Integer getGoodsUserId() {
		return this.goodsUserId;
	}

	public void setGoodsUserId(Integer goodsUserId) {
		this.goodsUserId = goodsUserId;
	}

	public String getGoodsDel() {
		return this.goodsDel;
	}

	public void setGoodsDel(String goodsDel) {
		this.goodsDel = goodsDel;
	}

	public String getFujian() {
		System.out.println("fujian:" + fujian);
		return fujian;
	}

	public void setFujian(String fujian) {
		this.fujian = fujian;
	}

}